{{ if .Values.secret.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "cert-manager-webhook-bunny.name" . }}
    chart: {{ include "cert-manager-webhook-bunny.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  api-key: {{ .Values.secret.apiKey }}
{{ end }}